basePath: /
definitions:
  dtos.AddEventStaffRequest:
    properties:
      event_id:
        type: integer
      staff_emails:
        items:
          type: string
        type: array
    type: object
  dtos.AuthRequest:
    properties:
      username:
        type: string
    type: object
  dtos.CreateEventRequest:
    properties:
      calendar_id:
        type: integer
      contact_information:
        type: string
      date:
        type: string
      description:
        type: string
      location:
        type: string
      name:
        type: string
      organizer_id:
        type: integer
      time:
        type: string
    type: object
  dtos.CreateSeriesRequest:
    properties:
      description:
        type: string
      image_url:
        type: string
      name:
        type: string
      organizer_id:
        type: integer
    type: object
  dtos.EventResponse:
    properties:
      calendar:
        type: string
      contact_information:
        type: string
      date:
        type: string
      description:
        type: string
      id:
        type: integer
      location:
        type: string
      message:
        type: string
      name:
        type: string
      status:
        type: string
      time:
        type: string
    type: object
  dtos.RaveResponse:
    type: object
  dtos.UpdateEventRequest:
    properties:
      contact_information:
        type: string
      date:
        type: string
      description:
        type: string
      location:
        type: string
      name:
        type: string
      organizer_id:
        type: integer
      time:
        type: string
    type: object
host: localhost:8082
info:
  contact:
    email: unavailable
    name: API Support
    url: https://www.thepartybank.com
  description: Partybank Organizer Service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Partybank Organizer Service
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user
      parameters:
      - description: Auth tags
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/dtos.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
      summary: Authenticate user
      tags:
      - Auth
  /auth/validate-otp:
    get:
      consumes:
      - application/json
      description: Validate Otp
      parameters:
      - description: otp code
        in: query
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
      summary: Validate Otp
      tags:
      - Auth
  /event/organizer:
    get:
      consumes:
      - application/json
      description: Get all Events for organizer
      parameters:
      - description: organizerId
        in: query
        name: organizerId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.EventResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
      security:
      - Bearer: []
      summary: Get all Events for organizer
      tags:
      - Events
  /protected/event:
    post:
      consumes:
      - application/json
      description: Adds Event
      parameters:
      - description: Event tags
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateEventRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
      security:
      - Bearer: []
      summary: Add Event
      tags:
      - Events
  /protected/event/{id}:
    get:
      consumes:
      - application/json
      description: Get Event By id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.EventResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
      security:
      - Bearer: []
      summary: Get Event By id
      tags:
      - Events
    put:
      consumes:
      - application/json
      description: Edits Event
      parameters:
      - description: Event tags
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateEventRequest'
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.EventResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
      security:
      - Bearer: []
      summary: Edit Event
      tags:
      - Events
  /protected/event/staff:
    post:
      consumes:
      - application/json
      description: Adds Event Staff
      parameters:
      - description: Organizer tags
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/dtos.AddEventStaffRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
      security:
      - Bearer: []
      summary: Add Event Staff
      tags:
      - Organizer
  /protected/series:
    post:
      consumes:
      - application/json
      description: Adds New Series
      parameters:
      - description: Series tags
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateSeriesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
      security:
      - Bearer: []
      summary: Add New Series
      tags:
      - Series
  /protected/series/{id}:
    get:
      consumes:
      - application/json
      description: Get Series by id
      parameters:
      - description: series id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.RaveResponse'
      security:
      - Bearer: []
      summary: Get Series by id
      tags:
      - Series
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
